name: Build APK Super Fix
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev unzip autoconf libtool pkg-config libffi-dev
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33 setuptools==65.5.0

      - name: Fix buildozer.spec
        run: |
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,openssl/' buildozer.spec
          sed -i 's/# android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/android.api = 31/android.api = 33/' buildozer.spec
          # Force use of stable p4a branch
          sed -i 's/p4a.branch = master/p4a.branch = release-2022.12.20/' buildozer.spec

      - name: Build APK
        run: |
          # Force Java 17
          export JAVA_HOME=$JAVA_HOME_17_X64
          export ANDROID_NDK_HOME=""
          export ANDROID_NDK=""
          yes | buildozer android debug > build.log 2>&1 || (tail -n 200 build.log && exit 1)

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk

      - name: Upload Build Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
